#!/bin/bash

if [[ "$1" == "" ]]; then
  echo "Provide swagger yaml filename"
  exit 0
fi

yaml2json - < $1 | json validate --schema-file schemas/exchangeServiceSchemaDefinition.json --document-file /dev/stdin
