---
swagger: "2.0"
info:
  description: Nordpool market hourly price API
  version: 0.3.0
  title: Nordpool Hourly price API
  termsOfService: https://hf00j9q9vk.execute-api.ap-southeast-1.amazonaws.com/terms-of-service
  contact:
    name: API Team
    url: https://hf00j9q9vk.execute-api.ap-southeast-1.amazonaws.com/contact
    email: missing@missing.com
host: hf00j9q9vk.execute-api.ap-southeast-1.amazonaws.com
basePath: /dev/api/marketdata/page
schemes:
- https
paths:
  /10:
    get:
      summary: Get hourly pricing data
      description: Get Hourly pricing data
      operationId: getHourly
      produces:
      - application/json
      parameters:
      - name: content-type
        in: header
        description: content-type
        default: application/json
        type: string
      - name: currency
        in: query
        type: string
        description: currency to use
        default: EUR
      - name: endDate
        in: query
        type: string
        description: Day to get data for, dd-mm-yyy format
        required: true
      responses:
        default:
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
        200:
          description: OK
          schema:
            $ref: '#/definitions/SuccessResponse'
      security:
      - Bearer: []
definitions:
  SuccessResponse:
    description: SuccessResponse
    type: object
  ErrorResponse:
    description: Request error
    type: object
    properties:
      error:
        type: string
        description: Error message
      status:
        type: integer
        description: Response code
      type:
        type: string
        description: Error type
