---
swagger: "2.0"
info:
  description: Nordpool market hourly price API
  version: 0.3.0
  title: Nordpool Hourly price API
  termsOfService: https://hf00j9q9vk.execute-api.ap-southeast-1.amazonaws.com/terms-of-service
  contact:
    name: API Team
    url: https://hf00j9q9vk.execute-api.ap-southeast-1.amazonaws.com/contact
    email: missing@missing.com
host: hf00j9q9vk.execute-api.ap-southeast-1.amazonaws.com
basePath: /dev/api/marketdata/page
schemes:
- https
paths:
  /10:
    get:
      summary: Get hourly pricing data
      description: Get Hourly pricing data
      operationId: getHourly
      produces:
      - application/json
      parameters:
      - name: content-type
        in: header
        description: content-type
        default: application/json
        type: string
      - name: currency
        in: query
        type: string
        description: currency to use
        default: EUR
      - name: endDate
        in: query
        type: string
        description: Day to get data for, dd-mm-yyy format
        required: true
      responses:
        default:
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
        200:
          description: OK
          schema:
            $ref: '#/definitions/SuccessResponse'
      security:
      - Bearer: []
definitions:
  SuccessResponse:
    description: SuccessResponse
    type: object
    properties:
      data:
        type: object
        properties:
          Rows:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              required:
              - Name
              - StartTime
              - EndTime
              - DateTimeForData
              - DayNumber
              - StartTimeDate
              - IsExtraRow
              - IsNtcRow
              - EmptyValue
              properties:
                Columns:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                    - Index
                    - Scale
                    - IsDominatingDirection
                    - IsValid
                    - IsAdditionalData
                    - Behavior
                    - Name
                    - Value
                    - GroupHeader
                    - DisplayNegativeValueInBlue
                    - CombinedName
                    - DateTimeForData
                    - DisplayName
                    - DisplayNameOrDominatingDirection
                    - IsOfficial
                    - UseDashDisplayStyle
                    properties:
                      Index:
                        type: number
                      Scale:
                        type: number
                      SecondaryValue: []
                      IsDominatingDirection:
                        type: boolean
                      IsValid:
                        type: boolean
                      IsAdditionalData:
                        type: boolean
                      Behavior:
                        type: number
                      Name:
                        type: string
                        minLength: 1
                      Value:
                        type: string
                        minLength: 1
                      GroupHeader:
                        type: string
                      DisplayNegativeValueInBlue:
                        type: boolean
                      CombinedName:
                        type: string
                        minLength: 1
                      DateTimeForData:
                        type: string
                        minLength: 1
                      DisplayName:
                        type: string
                        minLength: 1
                      DisplayNameOrDominatingDirection:
                        type: string
                        minLength: 1
                      IsOfficial:
                        type: boolean
                      UseDashDisplayStyle:
                        type: boolean
                Name:
                  type: string
                  minLength: 1
                StartTime:
                  type: string
                  minLength: 1
                EndTime:
                  type: string
                  minLength: 1
                DateTimeForData:
                  type: string
                  minLength: 1
                DayNumber:
                  type: number
                StartTimeDate:
                  type: string
                  minLength: 1
                IsExtraRow:
                  type: boolean
                IsNtcRow:
                  type: boolean
                EmptyValue:
                  type: string
                Parent: []
            description: Rows
          IsDivided:
            type: boolean
            description: IsDivided
          SectionNames:
            type: array
            items:
              properties: []
            description: SectionNames
          EntityIDs:
            type: array
            items:
              properties: []
            description: EntityIDs
          DataStartdate:
            type: string
            minLength: 1
            description: DataStartdate
          DataEnddate:
            type: string
            minLength: 1
            description: DataEnddate
          AreaChanges:
            type: array
            items:
              properties: []
            description: AreaChanges
          Units:
            type: array
            items:
              properties: []
            description: Units
          LatestResultDate:
            type: string
            minLength: 1
            description: LatestResultDate
          ContainsPreliminaryValues:
            type: boolean
            description: ContainsPreliminaryValues
          ContainsExchangeRates:
            type: boolean
            description: ContainsExchangeRates
          ExchangeRateOfficial:
            type: string
            description: ExchangeRateOfficial
          ExchangeRatePreliminary:
            type: string
            description: ExchangeRatePreliminary
          ExchangeUnit:
            description: ExchangeUnit
          DateUpdated:
            type: string
            minLength: 1
            description: DateUpdated
          CombinedHeadersEnabled:
            type: boolean
            description: CombinedHeadersEnabled
          DataType:
            type: number
            description: DataType
          TimeZoneInformation:
            type: number
            description: TimeZoneInformation
        required:
        - Rows
        - IsDivided
        - SectionNames
        - EntityIDs
        - DataStartdate
        - DataEnddate
        - AreaChanges
        - Units
        - LatestResultDate
        - ContainsPreliminaryValues
        - ContainsExchangeRates
        - ExchangeRateOfficial
        - ExchangeRatePreliminary
        - DateUpdated
        - CombinedHeadersEnabled
        - DataType
        - TimeZoneInformation
        description: data
      cacheKey:
        type: string
        minLength: 1
        description: cacheKey
      conf:
        type: object
        properties:
          Id:
            type: string
            minLength: 1
            description: Id
          Name:
            description: Name
          Published:
            type: string
            minLength: 1
            description: Published
          ShowGraph:
            type: boolean
            description: ShowGraph
          ResolutionPeriod:
            type: object
            properties:
              Id:
                type: string
                minLength: 1
                description: Id
              Resolution:
                type: number
                description: Resolution
              Unit:
                type: number
                description: Unit
              PeriodNumber:
                type: number
                description: PeriodNumber
            required:
            - Id
            - Resolution
            - Unit
            - PeriodNumber
            description: ResolutionPeriod
          ResolutionPeriodY:
            type: object
            properties:
              Id:
                type: string
                minLength: 1
                description: Id
              Resolution:
                type: number
                description: Resolution
              Unit:
                type: number
                description: Unit
              PeriodNumber:
                type: number
                description: PeriodNumber
            required:
            - Id
            - Resolution
            - Unit
            - PeriodNumber
            description: ResolutionPeriodY
          Entities:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              required:
              - SecondaryProductBehavior
              - Id
              - Name
              - GroupHeader
              - DataUpdated
              - Drillable
              - Index
              - IndexForColumn
              - MinMaxDisabled
              - DisableNumberGroupSeparator
              - SecondaryTimeserieID
              - HasPreliminary
              - Scale
              - SecondaryScale
              - DataType
              - SecondaryDataType
              - LastUpdate
              - Unit
              - IsDominatingDirection
              - DisplayAsSeparatedColumn
              - EnableInChart
              - BlueNegativeValues
              properties:
                ProductType:
                  type: object
                  properties:
                    Id:
                      type: string
                      minLength: 1
                    Attributes:
                      type: array
                      uniqueItems: true
                      minItems: 1
                      items:
                        required:
                        - Id
                        - Name
                        - Role
                        - HasRoles
                        properties:
                          Id:
                            type: string
                            minLength: 1
                          Name:
                            type: string
                            minLength: 1
                          Role:
                            type: string
                          HasRoles:
                            type: boolean
                          Values:
                            type: array
                            items:
                              properties: []
                    Name:
                      type: string
                      minLength: 1
                    DisplayName:
                      type: string
                      minLength: 1
                  required:
                  - Id
                  - Attributes
                  - Name
                  - DisplayName
                SecondaryProductType:
                  type: object
                  properties:
                    Id:
                      type: string
                      minLength: 1
                    Attributes: []
                    Name:
                      type: string
                      minLength: 1
                    DisplayName:
                      type: string
                      minLength: 1
                  required:
                  - Id
                  - Name
                  - DisplayName
                SecondaryProductBehavior:
                  type: number
                Id:
                  type: string
                  minLength: 1
                Name:
                  type: string
                  minLength: 1
                GroupHeader:
                  type: string
                DataUpdated:
                  type: string
                  minLength: 1
                Attributes:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                    - Id
                    - Name
                    - HasRoles
                    - Role
                    - Value
                    properties:
                      Id:
                        type: string
                        minLength: 1
                      Name:
                        type: string
                        minLength: 1
                      HasRoles:
                        type: boolean
                      Role:
                        type: string
                      Value:
                        type: string
                        minLength: 1
                Drillable:
                  type: boolean
                DateRanges:
                  type: array
                  items:
                    properties: []
                Index:
                  type: number
                IndexForColumn:
                  type: number
                MinMaxDisabled:
                  type: boolean
                DisableNumberGroupSeparator:
                  type: number
                TimeserieID: []
                SecondaryTimeserieID:
                  type: string
                  minLength: 1
                HasPreliminary:
                  type: boolean
                TimeseriePreliminaryID: []
                Scale:
                  type: number
                SecondaryScale:
                  type: number
                DataType:
                  type: number
                SecondaryDataType:
                  type: number
                LastUpdate:
                  type: string
                  minLength: 1
                Unit:
                  type: string
                  minLength: 1
                IsDominatingDirection:
                  type: boolean
                DisplayAsSeparatedColumn:
                  type: boolean
                EnableInChart:
                  type: boolean
                BlueNegativeValues:
                  type: boolean
            description: Entities
          TableType:
            type: number
            description: TableType
          ExtraRows:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              required:
              - Id
              - Header
              properties:
                Id:
                  type: string
                  minLength: 1
                Header:
                  type: string
                  minLength: 1
                ColumnProducts:
                  type: array
                  items:
                    properties: []
            description: ExtraRows
          Filters:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              required:
              - Id
              - AttributeName
              - DefaultValue
              properties:
                Id:
                  type: string
                  minLength: 1
                AttributeName:
                  type: string
                  minLength: 1
                Values:
                  type: array
                  items:
                    properties: []
                DefaultValue:
                  type: string
                  minLength: 1
            description: Filters
          IsDrillDownEnabled:
            type: boolean
            description: IsDrillDownEnabled
          DrillDownMode:
            type: number
            description: DrillDownMode
          IsMinValueEnabled:
            type: boolean
            description: IsMinValueEnabled
          IsMaxValueEnabled:
            type: boolean
            description: IsMaxValueEnabled
          ValidYearsBack:
            type: number
            description: ValidYearsBack
          IsNtcEnabled:
            type: boolean
            description: IsNtcEnabled
          NtcProductType:
            type: object
            properties:
              Id:
                type: string
                minLength: 1
                description: Id
              Attributes:
                description: Attributes
              Name:
                type: string
                minLength: 1
                description: Name
              DisplayName:
                type: string
                minLength: 1
                description: DisplayName
            required:
            - Id
            - Name
            - DisplayName
            description: NtcProductType
          NtcHeader:
            type: string
            description: NtcHeader
          ShowTimelineGraph:
            type: number
            description: ShowTimelineGraph
          ExchangeMode:
            type: number
            description: ExchangeMode
          IsPivotTable:
            type: number
            description: IsPivotTable
          IsCombinedHeadersEnabled:
            type: number
            description: IsCombinedHeadersEnabled
          NtcFormat:
            type: number
            description: NtcFormat
          DisplayHourAlsoInUKTime:
            type: boolean
            description: DisplayHourAlsoInUKTime
        required:
        - Id
        - Published
        - ShowGraph
        - ResolutionPeriod
        - ResolutionPeriodY
        - Entities
        - TableType
        - ExtraRows
        - Filters
        - IsDrillDownEnabled
        - DrillDownMode
        - IsMinValueEnabled
        - IsMaxValueEnabled
        - ValidYearsBack
        - IsNtcEnabled
        - NtcProductType
        - NtcHeader
        - ShowTimelineGraph
        - ExchangeMode
        - IsPivotTable
        - IsCombinedHeadersEnabled
        - NtcFormat
        - DisplayHourAlsoInUKTime
        description: conf
      header:
        type: object
        properties:
          title:
            type: string
            minLength: 1
            description: title
          description:
            type: string
            minLength: 1
            description: description
          questionMarkInfo:
            type: string
            minLength: 1
            description: questionMarkInfo
        required:
        - title
        - description
        - questionMarkInfo
        description: header
      endDate:
        type: string
        minLength: 1
        description: endDate
      currency:
        type: string
        minLength: 1
        description: currency
      pageId:
        type: number
        description: pageId
    required:
    - data
    - cacheKey
    - conf
    - header
    - endDate
    - currency
    - pageId
  ErrorResponse:
    description: Request error
    type: object
    properties:
      error:
        type: string
        description: Error message
      status:
        type: integer
        description: Response code
      type:
        type: string
        description: Error type
